name = "AdaptiveRejectionSampling"
uuid = "c75e803d-635f-53bd-ab7d-544e482d8c75"
version = "0.1.1"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ForwardDiff = "0.10.1"
StatsBase = "0.26,0.27,0.28,0.29,0.30,0.31,0.32,0.33"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
